# Generated by Django 4.2.10 on 2024-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groceryapp', '0004_alter_carousel_image_alter_carousel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
