# Generated by Django 4.2.10 on 2024-02-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groceryapp', '0005_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
