# Generated by Django 4.2.10 on 2024-02-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groceryapp', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
